### ISSUE TITLE
如何列出项目中已安装的插件？

### ISSUE THREAD

**Issue by the-eric-kwok** [nonebot/nb-cli#138]
期待有一个 `nb plugin list` 的命令来做这件事
此外，移除插件和更新插件操作从已安装的插件列表中多选会容易很多

**Comment by yanyongyu** [comment]
暂时没有反查功能，因为目前pyproject里存储的信息不足以反查。

**Comment by the-eric-kwok** [comment]
```toml
[project]
name = "nb_bot"
version = "0.1.0"
description = "nb_bot"
readme = "README.md"
requires-python = ">=3.9, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = ["nonebot_plugin_autoreply", "nonebot_plugin_withdraw"]
plugin_dirs = []
builtin_plugins = ["echo"]
```

目前我看到我的 pyproject.toml 文件中记录了 plugins 数组，似乎是有做记录的？但不确定好不好实现，如果不好实现的话这个信息放在这里给后来者做个参考。
